name: Go Build and Release (Cross-platform)

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Платформы
        arch: [amd64, arm64]  # Архитектуры

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.25.4'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/*.go') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod tidy

    - name: Build Go Application (Cross-Platform)
      run: |
        case "${{ matrix.os }}" in
          "ubuntu-latest")
            GOOS=linux
            ext=""
            ;;
          "windows-latest")
            GOOS=windows
            ext=".exe"
            ;;
          "macos-latest")
            GOOS=darwin
            ext=""
            ;;
          *)
            echo "Unknown OS: ${{ matrix.os }}" >&2
            exit 1
            ;;
        esac
        GOARCH=${{ matrix.arch }}
        output="Arma-Reforger-api-${{ matrix.os }}-${GOARCH}${ext}"
        GOOS=$GOOS GOARCH=$GOARCH go build -o "$output"

    - name: Package the build into a directory
      run: |
        mkdir -p arma-reforger-api
        cp Arma-Reforger-api-${{ matrix.os }}-${{ matrix.arch }}* arma-reforger-api/
        cp config.json arma-reforger-api/
        cp -r Tools/ arma-reforger-api/ || true # || true на случай, если папки Tools нет в корне

    # Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Arma-Reforger-api-${{ matrix.os }}-${{ matrix.arch }}
        path: arma-reforger-api/
      

  # Новый job для релиза
  release:
    needs: build # Ждем успешного завершения сборки всех матриц
    runs-on: ubuntu-latest
    permissions:
      contents: write # Права на создание релиза в репозитории

    steps:
    - name: Download all build artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: false # Сохраняет структуру папок для каждого артефакта

    - name: Zip artifacts for release
      run: |
        cd artifacts
        # Проходим по всем скачанным папкам артефактов и создаем для них zip-архивы
        for dir in */; do
          dirname="${dir%/}"
          zip -r "${dirname}.zip" "$dirname"
        done

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/*.zip
        generate_release_notes: true # Автоматически сгенерирует changelog из коммитов
